version: '3.8'

services:
  image_resizer:
    container_name: image_resizer
    image: image_resizer:latest
    environment:
      APP_ENV: 'dev'
    ports:
      - "7788:80"
    build:
      context: ./
    volumes:
      - ./:/project
