index:
  path: /
  controller: App\Controller\AppController::index
  methods: GET

resize:
  path: /resize
  controller: App\Controller\AppController::resize
  methods: POST

media:
  path: /media/{filter}/{canonical_name}
  controller: App\Controller\AppController::media
  methods: GET

mediaCanonical:
  path: /media/{filter}/{unique_name}/{canonical_name}
  controller: App\Controller\AppController::mediaCanonical
  methods: GET